/**
 * Dashboard.jsx
 * ─────────────────────────────────────────────────────────────────────────────
 * Super Admin Executive Dashboard
 * 
 * Strict RBAC: Accessible exclusively to SUPER_ADMIN.
 * Displays:
 *  - Total Revenue generated by the Cafe & Bar
 *  - Total Valuation and Revenue metrics of Inventory Management (Shop)
 *  - Quick access hubs for HR Management, Inventory Management, Cafe Management, and Settings
 *  - Club court booking & membership metrics
 * ─────────────────────────────────────────────────────────────────────────────
 */

import React, { useEffect, useState, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { api } from '../services/api';
import { useAuth } from '../context/AuthContext';
import {
  Users, Trophy, DollarSign, TrendingUp,
  AlertTriangle, Clock, Calendar, Coffee, ShoppingBag,
  ArrowUpRight, Plus, CheckCircle2, RefreshCw, Activity,
  Layers, BadgeCheck, Settings, ChevronRight, Shield,
  ArrowRight, Sparkles, Eye, Box, AlertCircle
} from 'lucide-react';
import { getGreeting, todayLabel } from '../components/dashboard/dashboardUtils';

export default function Dashboard() {
  const navigate = useNavigate();
  const { user, club } = useAuth();

  // ── State ──────────────────────────────────────────────────────────────────
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState(null);

  // ── Fetch Dashboard Data ───────────────────────────────────────────────────
  const loadDashboard = useCallback(async () => {
    try {
      setLoading(true);
      setError(null);
      const res = await api.getDashboard();
      if (res?.success) {
        setData(res.data?.dashboard || res.data || res.dashboard);
      } else {
        setError(res?.message || 'Failed to fetch executive dashboard data');
      }
    } catch (e) {
      console.error('Executive dashboard fetch error:', e);
      setError(e?.message || 'Network error while connecting to club operations server');
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useEffect(() => {
    loadDashboard();
  }, [loadDashboard]);

  const handleRefresh = async () => {
    setRefreshing(true);
    await loadDashboard();
  };

  // ── Safe Data Extraction ───────────────────────────────────────────────────
  const kpis = data?.kpis || {};
  const cafeMetrics = data?.cafeMetrics || {
    totalRevenue: kpis.cafeRevenue || 0,
    todayRevenue: kpis.cafeTodayRevenue || 0,
    averageOrderValue: 0,
    preparingOrders: 0,
    servedOrders: 0,
    totalOrders: 0,
  };
  const inventoryMetrics = data?.inventoryMetrics || {
    totalValuation: kpis.inventoryValuation || 0,
    totalProducts: kpis.inventoryProductsCount || 0,
    totalStock: 0,
    lowStockCount: kpis.lowStockCount || 0,
    outOfStockCount: 0,
    totalAlerts: 0,
  };
  const hrMetrics = data?.hrMetrics || {
    totalEmployees: kpis.hrTotalStaff || 0,
    activeEmployees: 0,
    departmentsCount: 0,
    pendingLeavesCount: kpis.hrPendingLeaves || 0,
  };
  const alerts = data?.alerts || [];
  const recentActivity = data?.recentActivity || [];

  // Total club revenue (Combined Cafe + Bookings + Memberships)
  const totalRevenue = kpis.totalClubRevenue || (
    Number(cafeMetrics.totalRevenue || 0) +
    Number(kpis.monthlyRevenue || 0)
  );

  // ── Loading Screen ─────────────────────────────────────────────────────────
  if (loading && !data) {
    return (
      <div className="flex items-center justify-center min-h-[65vh]">
        <div className="text-center space-y-3">
          <div
            className="w-10 h-10 rounded-full border-3 animate-spin mx-auto"
            style={{ borderColor: 'var(--color-primary)', borderTopColor: 'transparent' }}
          />
          <p className="text-xs font-semibold text-gray-500">
            Loading Super Admin Executive Dashboard…
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6 max-w-[1400px] mx-auto animate-fade-in pb-10">

      {/* ══════════════════════════════════════════════════════════════════════
          1. SUPER ADMIN EXECUTIVE BANNER
      ══════════════════════════════════════════════════════════════════════ */}
      <div className="bg-gradient-to-r from-[#3B1E34] via-[#4D2845] to-[#5C3252] text-white p-6 sm:p-7 rounded-2xl shadow-sm relative overflow-hidden border border-[#5C3252]">
        <div className="absolute -right-8 -bottom-8 w-60 h-60 rounded-full bg-white/5 pointer-events-none" />

        <div className="relative z-10 flex flex-col md:flex-row md:items-center justify-between gap-5">
          <div>
            <div className="flex items-center gap-2.5 flex-wrap">
              <span className="px-2.5 py-0.5 rounded-full bg-white/15 text-white text-[11px] font-bold tracking-wide uppercase border border-white/20">
                Super Admin Center
              </span>
              <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full bg-emerald-500/20 text-emerald-300 text-[11px] font-bold border border-emerald-500/30">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
                Live Club Operations
              </span>
            </div>
            <h1 className="text-xl sm:text-2xl font-black mt-2 tracking-tight">
              {club?.name || data?.club?.name || 'Skyline Sports Club'}
            </h1>
            <p className="text-purple-100/80 text-xs sm:text-[13px] mt-1">
              {getGreeting()}, <strong className="text-white">{user?.name || 'Administrator'}</strong> · {todayLabel()}
            </p>
          </div>

          {/* Quick Actions Navigation Strip for Super Admin */}
          <div className="flex flex-wrap items-center gap-2.5">
            <button
              onClick={handleRefresh}
              disabled={refreshing}
              className="px-3.5 py-2 rounded-xl bg-white/10 hover:bg-white/20 border border-white/20 text-white text-xs font-semibold flex items-center gap-1.5 transition-all cursor-pointer"
              title="Sync club metrics"
            >
              <RefreshCw size={14} className={refreshing ? 'animate-spin' : ''} />
              <span>Sync</span>
            </button>

            <button
              onClick={() => navigate('/cafe')}
              className="px-3.5 py-2 rounded-xl bg-white/10 hover:bg-white/20 border border-white/20 text-white text-xs font-semibold flex items-center gap-1.5 transition-all cursor-pointer"
            >
              <Coffee size={14} className="text-amber-300" />
              <span>Cafe</span>
            </button>

            <button
              onClick={() => navigate('/shop')}
              className="px-3.5 py-2 rounded-xl bg-white/10 hover:bg-white/20 border border-white/20 text-white text-xs font-semibold flex items-center gap-1.5 transition-all cursor-pointer"
            >
              <ShoppingBag size={14} className="text-blue-300" />
              <span>Inventory</span>
            </button>

            <button
              onClick={() => navigate('/staff')}
              className="px-3.5 py-2 rounded-xl bg-white/10 hover:bg-white/20 border border-white/20 text-white text-xs font-semibold flex items-center gap-1.5 transition-all cursor-pointer"
            >
              <BadgeCheck size={14} className="text-emerald-300" />
              <span>Staff &amp; HR</span>
            </button>

            <button
              onClick={() => navigate('/settings')}
              className="px-3.5 py-2 rounded-xl bg-white hover:bg-gray-100 text-[#714B67] text-xs font-bold flex items-center gap-1.5 shadow-xs transition-all cursor-pointer"
            >
              <Settings size={14} />
              <span>Settings</span>
            </button>
          </div>
        </div>
      </div>

      {/* Error notification if any */}
      {error && (
        <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-xl flex items-center gap-2.5 text-xs font-semibold">
          <AlertCircle size={16} />
          <span>{error}</span>
        </div>
      )}

      {/* ══════════════════════════════════════════════════════════════════════
          2. TOP 4 KEY REVENUE & EXECUTIVE METRICS
      ══════════════════════════════════════════════════════════════════════ */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">

        {/* Card 1: Revenue Generated by Cafe & Bar */}
        <div
          onClick={() => navigate('/cafe')}
          className="bg-white rounded-2xl p-5 border border-[#E5E7EB] border-t-4 border-t-amber-500 shadow-xs hover:shadow-md transition-all cursor-pointer flex flex-col justify-between group"
        >
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-bold text-gray-500 uppercase tracking-wider">
              Cafe &amp; Bar Revenue
            </span>
            <div className="w-8 h-8 rounded-xl bg-amber-50 text-amber-600 flex items-center justify-center group-hover:scale-105 transition-transform">
              <Coffee size={16} />
            </div>
          </div>
          <div className="mt-3">
            <div className="text-2xl font-black text-gray-900 tracking-tight">
              ₹{Number(cafeMetrics.totalRevenue || 0).toLocaleString('en-IN')}
            </div>
            <div className="flex items-center justify-between mt-2 pt-2 border-t border-gray-100 text-[11px]">
              <span className="text-gray-500">Today's Sales:</span>
              <span className="font-bold text-emerald-600">
                +₹{Number(cafeMetrics.todayRevenue || 0).toLocaleString('en-IN')}
              </span>
            </div>
          </div>
        </div>

        {/* Card 2: Inventory Management Valuation & Stock */}
        <div
          onClick={() => navigate('/shop')}
          className="bg-white rounded-2xl p-5 border border-[#E5E7EB] border-t-4 border-t-blue-500 shadow-xs hover:shadow-md transition-all cursor-pointer flex flex-col justify-between group"
        >
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-bold text-gray-500 uppercase tracking-wider">
              Inventory Valuation
            </span>
            <div className="w-8 h-8 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center group-hover:scale-105 transition-transform">
              <ShoppingBag size={16} />
            </div>
          </div>
          <div className="mt-3">
            <div className="text-2xl font-black text-gray-900 tracking-tight">
              ₹{Number(inventoryMetrics.totalValuation || 0).toLocaleString('en-IN')}
            </div>
            <div className="flex items-center justify-between mt-2 pt-2 border-t border-gray-100 text-[11px]">
              <span className="text-gray-500">{inventoryMetrics.totalProducts} Catalog Products</span>
              <span className={`font-bold ${inventoryMetrics.lowStockCount > 0 ? 'text-amber-600' : 'text-emerald-600'}`}>
                {inventoryMetrics.lowStockCount > 0 ? `${inventoryMetrics.lowStockCount} Low Stock` : 'All Stocked'}
              </span>
            </div>
          </div>
        </div>

        {/* Card 3: Total Consolidated Club Revenue */}
        <div className="bg-white rounded-2xl p-5 border border-[#E5E7EB] border-t-4 border-t-[#714B67] shadow-xs flex flex-col justify-between">
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-bold text-gray-500 uppercase tracking-wider">
              Total Club Revenue
            </span>
            <div className="w-8 h-8 rounded-xl bg-purple-50 text-[#714B67] flex items-center justify-center">
              <DollarSign size={16} />
            </div>
          </div>
          <div className="mt-3">
            <div className="text-2xl font-black text-gray-900 tracking-tight">
              ₹{Number(totalRevenue || 0).toLocaleString('en-IN')}
            </div>
            <div className="flex items-center justify-between mt-2 pt-2 border-t border-gray-100 text-[11px] text-gray-500">
              <span>Cafe + Bookings + Members</span>
              <span className="font-semibold text-emerald-600 flex items-center gap-0.5">
                <TrendingUp size={12} /> Live
              </span>
            </div>
          </div>
        </div>

        {/* Card 4: HR & Workforce Strength */}
        <div
          onClick={() => navigate('/staff')}
          className="bg-white rounded-2xl p-5 border border-[#E5E7EB] border-t-4 border-t-emerald-500 shadow-xs hover:shadow-md transition-all cursor-pointer flex flex-col justify-between group"
        >
          <div className="flex items-center justify-between">
            <span className="text-[11px] font-bold text-gray-500 uppercase tracking-wider">
              Staff &amp; Workforce
            </span>
            <div className="w-8 h-8 rounded-xl bg-emerald-50 text-emerald-600 flex items-center justify-center group-hover:scale-105 transition-transform">
              <BadgeCheck size={16} />
            </div>
          </div>
          <div className="mt-3">
            <div className="text-2xl font-black text-gray-900 tracking-tight">
              {hrMetrics.totalEmployees || 0} Staff
            </div>
            <div className="flex items-center justify-between mt-2 pt-2 border-t border-gray-100 text-[11px]">
              <span className="text-gray-500">{hrMetrics.departmentsCount || 7} Departments</span>
              <span className={`font-bold ${hrMetrics.pendingLeavesCount > 0 ? 'text-amber-600' : 'text-gray-400'}`}>
                {hrMetrics.pendingLeavesCount > 0 ? `${hrMetrics.pendingLeavesCount} Leaves Pending` : '0 Pending Leaves'}
              </span>
            </div>
          </div>
        </div>

      </div>

      {/* ══════════════════════════════════════════════════════════════════════
          3. SUPER ADMIN CORE MODULE HUBS (CAFE & INVENTORY PROMINENT)
      ══════════════════════════════════════════════════════════════════════ */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">

        {/* ── HUB 1: CAFE MANAGEMENT & REVENUE HUB ── */}
        <div className="bg-white rounded-2xl border border-gray-200 shadow-xs p-6 flex flex-col justify-between space-y-5">
          <div>
            <div className="flex items-center justify-between pb-4 border-b border-gray-100">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-amber-50 text-amber-700 flex items-center justify-center font-bold">
                  <Coffee size={20} />
                </div>
                <div>
                  <h3 className="text-base font-bold text-gray-900">Cafe Management &amp; Sales</h3>
                  <p className="text-xs text-gray-500">Live food &amp; beverage sales, kitchen orders, and menu revenue</p>
                </div>
              </div>
              <span className="px-2.5 py-1 rounded-full bg-amber-50 text-amber-800 text-[11px] font-bold border border-amber-200">
                Active Module
              </span>
            </div>

            {/* Cafe Sub-metrics Grid */}
            <div className="grid grid-cols-3 gap-3 mt-4">
              <div className="p-3.5 rounded-xl bg-[#F5F6FA] border border-gray-200/80">
                <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">Total Cafe Sales</span>
                <span className="text-lg font-black text-gray-900 mt-1 block">
                  ₹{Number(cafeMetrics.totalRevenue || 0).toLocaleString('en-IN')}
                </span>
              </div>
              <div className="p-3.5 rounded-xl bg-[#F5F6FA] border border-gray-200/80">
                <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">Today's Revenue</span>
                <span className="text-lg font-black text-emerald-700 mt-1 block">
                  ₹{Number(cafeMetrics.todayRevenue || 0).toLocaleString('en-IN')}
                </span>
              </div>
              <div className="p-3.5 rounded-xl bg-[#F5F6FA] border border-gray-200/80">
                <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">Kitchen Orders</span>
                <span className="text-lg font-black text-amber-700 mt-1 block">
                  {cafeMetrics.preparingOrders || 0} Preparing
                </span>
              </div>
            </div>

            <div className="mt-4 p-3.5 rounded-xl bg-amber-50/60 border border-amber-100 flex items-center justify-between text-xs text-amber-900">
              <div className="flex items-center gap-2">
                <Sparkles size={14} className="text-amber-600 shrink-0" />
                <span>Track table orders, combo deals, and member discounts in real time.</span>
              </div>
              <span className="font-bold">{cafeMetrics.servedOrders || 0} Served Orders</span>
            </div>
          </div>

          <button
            onClick={() => navigate('/cafe')}
            className="w-full py-2.5 px-4 rounded-xl bg-[#714B67] hover:bg-[#57344f] text-white text-xs font-bold flex items-center justify-center gap-2 transition-all shadow-xs cursor-pointer"
          >
            <span>Open Cafe Management</span>
            <ArrowRight size={14} />
          </button>
        </div>

        {/* ── HUB 2: INVENTORY MANAGEMENT & VALUATION HUB ── */}
        <div className="bg-white rounded-2xl border border-gray-200 shadow-xs p-6 flex flex-col justify-between space-y-5">
          <div>
            <div className="flex items-center justify-between pb-4 border-b border-gray-100">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-blue-50 text-blue-700 flex items-center justify-center font-bold">
                  <ShoppingBag size={20} />
                </div>
                <div>
                  <h3 className="text-base font-bold text-gray-900">Inventory Management &amp; Pro Shop</h3>
                  <p className="text-xs text-gray-500">Retail equipment catalog, stock adjustments, and asset valuation</p>
                </div>
              </div>
              <span className="px-2.5 py-1 rounded-full bg-blue-50 text-blue-800 text-[11px] font-bold border border-blue-200">
                Active Module
              </span>
            </div>

            {/* Inventory Sub-metrics Grid */}
            <div className="grid grid-cols-3 gap-3 mt-4">
              <div className="p-3.5 rounded-xl bg-[#F5F6FA] border border-gray-200/80">
                <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">Asset Valuation</span>
                <span className="text-lg font-black text-gray-900 mt-1 block">
                  ₹{Number(inventoryMetrics.totalValuation || 0).toLocaleString('en-IN')}
                </span>
              </div>
              <div className="p-3.5 rounded-xl bg-[#F5F6FA] border border-gray-200/80">
                <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">Total Products</span>
                <span className="text-lg font-black text-gray-900 mt-1 block">
                  {inventoryMetrics.totalProducts || 0} Items
                </span>
              </div>
              <div className="p-3.5 rounded-xl bg-[#F5F6FA] border border-gray-200/80">
                <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">Stock Thresholds</span>
                <span className={`text-lg font-black mt-1 block ${inventoryMetrics.lowStockCount > 0 ? 'text-amber-600' : 'text-emerald-700'}`}>
                  {inventoryMetrics.lowStockCount || 0} Low Stock
                </span>
              </div>
            </div>

            <div className="mt-4 p-3.5 rounded-xl bg-blue-50/60 border border-blue-100 flex items-center justify-between text-xs text-blue-900">
              <div className="flex items-center gap-2">
                <Box size={14} className="text-blue-600 shrink-0" />
                <span>Automatic restock alerts triggered when items dip below minimum inventory level.</span>
              </div>
              <span className="font-bold">{inventoryMetrics.totalStock || 0} Units In Stock</span>
            </div>
          </div>

          <button
            onClick={() => navigate('/shop')}
            className="w-full py-2.5 px-4 rounded-xl bg-[#714B67] hover:bg-[#57344f] text-white text-xs font-bold flex items-center justify-center gap-2 transition-all shadow-xs cursor-pointer"
          >
            <span>Open Inventory Management</span>
            <ArrowRight size={14} />
          </button>
        </div>

      </div>

      {/* ══════════════════════════════════════════════════════════════════════
          4. SECONDARY SUPER ADMIN HUBS (HR MANAGEMENT & SETTINGS SECTION)
      ══════════════════════════════════════════════════════════════════════ */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">

        {/* ── HUB 3: HR MANAGEMENT & WORKFORCE HUB ── */}
        <div className="bg-white rounded-2xl border border-gray-200 shadow-xs p-6 flex flex-col justify-between space-y-5">
          <div>
            <div className="flex items-center justify-between pb-4 border-b border-gray-100">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-emerald-50 text-emerald-700 flex items-center justify-center font-bold">
                  <BadgeCheck size={20} />
                </div>
                <div>
                  <h3 className="text-base font-bold text-gray-900">HR &amp; Staff Management</h3>
                  <p className="text-xs text-gray-500">Employee credentials, department rosters, leaves, and payroll</p>
                </div>
              </div>
              <button
                onClick={() => navigate('/staff')}
                className="text-xs font-bold text-[#714B67] hover:underline flex items-center gap-1"
              >
                <span>View All</span>
                <ChevronRight size={14} />
              </button>
            </div>

            <div className="grid grid-cols-2 gap-3 mt-4">
              <div className="p-3.5 rounded-xl bg-[#F5F6FA] border border-gray-200/80">
                <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">Staff Directory</span>
                <span className="text-xl font-black text-gray-900 mt-1 block">
                  {hrMetrics.totalEmployees || 0} Registered Staff
                </span>
                <span className="text-[11px] text-gray-400 mt-1 block">Across all active club departments</span>
              </div>
              <div className="p-3.5 rounded-xl bg-[#F5F6FA] border border-gray-200/80">
                <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">Leave Requests</span>
                <span className={`text-xl font-black mt-1 block ${hrMetrics.pendingLeavesCount > 0 ? 'text-amber-600' : 'text-emerald-700'}`}>
                  {hrMetrics.pendingLeavesCount || 0} Pending Review
                </span>
                <span className="text-[11px] text-gray-400 mt-1 block">Approval workflow managed by HR</span>
              </div>
            </div>
          </div>

          <button
            onClick={() => navigate('/staff')}
            className="w-full py-2.5 px-4 rounded-xl border border-gray-300 hover:bg-gray-50 text-gray-800 text-xs font-bold flex items-center justify-center gap-2 transition-all cursor-pointer"
          >
            <span>Open HR &amp; Workforce System</span>
            <ArrowRight size={14} />
          </button>
        </div>

        {/* ── HUB 4: SETTINGS & CLUB CONFIGURATION HUB ── */}
        <div className="bg-white rounded-2xl border border-gray-200 shadow-xs p-6 flex flex-col justify-between space-y-5">
          <div>
            <div className="flex items-center justify-between pb-4 border-b border-gray-100">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-purple-50 text-[#714B67] flex items-center justify-center font-bold">
                  <Settings size={20} />
                </div>
                <div>
                  <h3 className="text-base font-bold text-gray-900">Settings &amp; Module Configuration</h3>
                  <p className="text-xs text-gray-500">Club details, active feature modules, payment gateway, and security</p>
                </div>
              </div>
              <button
                onClick={() => navigate('/settings')}
                className="text-xs font-bold text-[#714B67] hover:underline flex items-center gap-1"
              >
                <span>Edit</span>
                <ChevronRight size={14} />
              </button>
            </div>

            <div className="grid grid-cols-2 gap-3 mt-4">
              <div className="p-3.5 rounded-xl bg-[#F5F6FA] border border-gray-200/80">
                <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">Club Identity</span>
                <span className="text-sm font-bold text-gray-900 mt-1 block truncate">
                  {club?.name || 'Skyline Sports Club'}
                </span>
                <span className="text-[11px] text-gray-400 mt-0.5 block truncate">
                  {club?.email || 'admin@skylinesports.com'}
                </span>
              </div>
              <div className="p-3.5 rounded-xl bg-[#F5F6FA] border border-gray-200/80">
                <span className="text-[10px] font-bold text-gray-400 uppercase tracking-wider block">Active Modules</span>
                <span className="text-sm font-bold text-emerald-700 mt-1 block">
                  Cafe, Shop, HR &amp; Courts
                </span>
                <span className="text-[11px] text-gray-400 mt-0.5 block">Toggle modules anytime</span>
              </div>
            </div>
          </div>

          <button
            onClick={() => navigate('/settings')}
            className="w-full py-2.5 px-4 rounded-xl border border-gray-300 hover:bg-gray-50 text-gray-800 text-xs font-bold flex items-center justify-center gap-2 transition-all cursor-pointer"
          >
            <span>Open Club Settings</span>
            <ArrowRight size={14} />
          </button>
        </div>

      </div>

      {/* ══════════════════════════════════════════════════════════════════════
          5. OPERATIONAL AUDIT LOG & RECENT ACTIVITY
      ══════════════════════════════════════════════════════════════════════ */}
      <div className="bg-white rounded-2xl border border-gray-200 shadow-xs p-6 space-y-4">
        <div className="flex items-center justify-between pb-3 border-b border-gray-100">
          <div className="flex items-center gap-2">
            <Activity size={18} className="text-[#714B67]" />
            <h3 className="text-sm font-bold text-gray-900">Recent Club Operational Activity</h3>
          </div>
          <span className="text-[11px] text-gray-400">Live Audit Stream</span>
        </div>

        {recentActivity.length === 0 ? (
          <div className="p-8 text-center bg-[#F5F6FA] rounded-xl text-gray-400 text-xs">
            No recent activity logged. Live orders, bookings, and inventory updates will appear here.
          </div>
        ) : (
          <div className="divide-y divide-gray-100 max-h-72 overflow-y-auto pr-1">
            {recentActivity.slice(0, 8).map((log, idx) => (
              <div key={idx} className="py-2.5 flex items-center justify-between text-xs">
                <div className="flex items-center gap-2.5">
                  <span className="w-2 h-2 rounded-full bg-[#714B67]" />
                  <span className="font-semibold text-gray-800">{log.action || log.description || 'System Event'}</span>
                  <span className="text-[11px] text-gray-400">({log.userName || log.user || 'Admin'})</span>
                </div>
                <span className="text-[10px] text-gray-400 font-mono">
                  {log.timestamp ? new Date(log.timestamp).toLocaleTimeString() : 'Just now'}
                </span>
              </div>
            ))}
          </div>
        )}
      </div>

    </div>
  );
}
