/**
 * Application Constants
 * Centralized role and module definitions
 */

export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  RECEPTIONIST: "RECEPTIONIST",
  SHOP_INVENTORY_MANAGER: "SHOP_INVENTORY_MANAGER",
  BAR_CAFETERIA_STAFF: "BAR_CAFETERIA_STAFF",
  HR_MANAGER: "HR_MANAGER",
  ACCOUNTANT: "ACCOUNTANT",
};

export const MODULES = {
  MEMBERSHIP: "MEMBERSHIP",
  COURT_BOOKING: "COURT_BOOKING",
  SHOP: "SHOP",
  BAR: "BAR",
  HR: "HR",
  ACCOUNTING: "ACCOUNTING",
};

// Role display names for frontend
export const ROLE_DISPLAY_NAMES = {
  [ROLES.SUPER_ADMIN]: "Super Admin",
  [ROLES.RECEPTIONIST]: "Receptionist",
  [ROLES.SHOP_INVENTORY_MANAGER]: "Shop / Inventory Manager",
  [ROLES.BAR_CAFETERIA_STAFF]: "Bar & Cafeteria Staff",
  [ROLES.HR_MANAGER]: "HR Manager",
  [ROLES.ACCOUNTANT]: "Accountant",
};

// Module display names
export const MODULE_DISPLAY_NAMES = {
  [MODULES.MEMBERSHIP]: "Membership Management",
  [MODULES.COURT_BOOKING]: "Court & Booking Management",
  [MODULES.SHOP]: "Shop / Inventory Management",
  [MODULES.BAR]: "Bar & Cafeteria Management",
  [MODULES.HR]: "HR & Staff Management",
  [MODULES.ACCOUNTING]: "Accounting & Finance",
};

// Role to Module mapping
export const ROLE_MODULE_MAP = {
  [ROLES.SUPER_ADMIN]: ["ALL"],
  [ROLES.RECEPTIONIST]: [MODULES.MEMBERSHIP, MODULES.COURT_BOOKING],
  [ROLES.SHOP_INVENTORY_MANAGER]: [MODULES.SHOP],
  [ROLES.BAR_CAFETERIA_STAFF]: [MODULES.BAR],
  [ROLES.HR_MANAGER]: [MODULES.HR],
  [ROLES.ACCOUNTANT]: [MODULES.ACCOUNTING],
};

// Module to Prisma field mapping
export const MODULE_DB_MAP = {
  [MODULES.MEMBERSHIP]: "membership",
  [MODULES.COURT_BOOKING]: "courtBooking",
  [MODULES.SHOP]: "shop",
  [MODULES.BAR]: "bar",
  [MODULES.HR]: "hr",
  [MODULES.ACCOUNTING]: "accounting",
};

// Error codes
export const ERROR_CODES = {
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_ROLE: "INVALID_ROLE",
  ROLE_NOT_ALLOWED: "ROLE_NOT_ALLOWED",
  MODULE_DISABLED: "MODULE_DISABLED",
  INSUFFICIENT_PERMISSION: "INSUFFICIENT_PERMISSION",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  CLUB_NOT_FOUND: "CLUB_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_MODULE: "INVALID_MODULE",
  MODULE_DEPENDENCY_ERROR: "MODULE_DEPENDENCY_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  SERVER_ERROR: "SERVER_ERROR",
};

// HTTP Status Codes
export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
};
